### ISSUE TITLE
ia-upload convert pdf to djvu and uploaded as 0 × 0 pixels file

### ISSUE THREAD

**Issue by jayantanth** [wikisource/ia-upload#11]
Today I have uploaded one file https://commons.wikimedia.org/wiki/File:Bub_wbpln_10689_5591.djvu through http://tools.wmflabs.org/ia-upload/, but it converted pdf to djvu and uploaded as 0 × 0 pixels file without no page.

**Comment by nemobis** [comment]
Jayanta Nath, 14/08/2016 18:37:
> Today I have uploaded one file
> https://commons.wikimedia.org/wiki/File:Bub_wbpln_10689_5591.djvu
> through http://tools.wmflabs.org/ia-upload/, but it converted pdf to
> djvu and uploaded as 0 × 0 pixels file without no page.

pdf2djvu 0.7.21 (DjVuLibre 3.5.25, Poppler 0.34.0, PStreams 0.8.1) 
created the DjVu correctly for me; I reuploaded over your file. Does 
ia-upload need a new version or what?

**Comment by samwilson** [comment]
Has this problem happened with any other PDF conversions? Does it still happen?

As an alternative, you can now elect to create the DjVu from the IA's JP2 files rather than the PDF. This may get around the problem.

If there is a problem with converting from PDF it is likely to belong to http://tools.wmflabs.org/phetools/pdf_to_djvu_cgi.py rather than this tool, as this one is just handing off PDF → DjVu to that tool.

**Comment by samwilson** [comment]
I haven't seen this problem crop up again, so I'll close it as "probably fixed somehow". :-)

If anyone gets it again, please create a new issue on Phabricator.
