### ISSUE TITLE
The conversion from PDF to DJVU loses too much quality

### ISSUE THREAD

**Issue by Aubreymcfato** [wikisource/ia-upload#14]
I'm doing a Wikisource course with several librarians, and using this tool a lot. It's grat as usual, but there is a real issue: when you take a PDF from IA, and the tool converts in DJVU, the DJVU is pretty useless. The quality is incredibly low, even when the original scan is really good. I'm re-converting manually all these djvu (with (https://it.wikisource.org/wiki/Progetto:Bot/Programmi_in_Python_per_i_bot/jp2todjvu.py)[Alex Brollo script]) because otherwise they are unreadable. Is it possible to upload directly the PDF? Or to integrate Alex's script into the ia-upload tool?

**Comment by samwilson** [comment]
I think integrating Alex's script is the best way to go. Perhaps adding it as a queue that's processed server-side so that users aren't left waiting for too long?

Kaldari raised the question about the process depending on the `*_djvu.xml` files being available from IA for new (non-DjVu) items — is there any guarantee that they'll keep producing these? I guess we can cross that bridge when we get to it though.

**Comment by nemobis** [comment]
Sam Wilson, 25/01/2017 03:44:
> Kaldari raised the question about the process depending on the
> |*_djvu.xml| files being available from IA for new (non-DjVu) items — is
> there any guarantee that they'll keep producing these?

_djvu.xml has nothing to do with DjVu itself, it's the OCR data produced 
by FineReader and packaged by IA.

**Comment by samwilson** [comment]
But it's produced *in order that* they can produce DjVu files isn't it? And so it's no longer required, and could be dropped at some point? I realise that it's not part of DjVu itself, but I sort of assumed that it hasn't got any other purpose. It'd be nice to know that they're going to carry on generating them, is all.

If they're not, we would have to look at a workflow that also incorporates OCR, I guess — which we don't want to have to do (and I suspect we don't).

**Comment by Tpt** [comment]
> I think integrating Alex's script is the best way to go.
Yes, we should definitely do something similar to Alex's script, as a background task.

> [about _djvu.xml] but I sort of assumed that it hasn't got any other purpose.
They are quite useful because these files provides a mapping between the text layer and the position of each word on the scan image in a much more usable way than PDF. It is imho valuable per se.

**Comment by nemobis** [comment]
Sam Wilson, 25/01/2017 09:03:
> But it's produced /in order that/ they can produce DjVu files isn't it?

It used to be so but no longer, as explained in the announcement 
https://archive.org/post/1053214/djvu-files-for-new-uploads

**Comment by samwilson** [comment]
@nemobis sorry, yes, I realised that they are no longer needed for making DjVu. I hadn't realised that they have in fact committed to continuing to produce the `_djvu.xml` files:

> We will continue to make the _djvu.xml files that are word-based OCR output with coordinates, and we have an improved way of making .txt files that will work in more cases (currently it depends on the djvu file being created, and this has not been very consistent).

That's all I was worried about—that we don't want to build a workflow around a file that they aren't planning to continue to produce. But it sounds like they need the `_djvu.xml` as a step towards making the `.txt`.

So all is good! :-)

**Comment by samwilson** [comment]
A test installation is now configured at http://tools.wmflabs.org/ia-upload/test/

It is currently downloading, creating the high-quality DjVu, and uploading to Commons. Bit of other cleaning up of the code to do. Would love any feedback so far.

Need to figure out how often to schedule the background task to run. Every 5 minutes? And some way of showing progress to the user is required I think, otherwise it just looks like it's sitting there.
