### ISSUE TITLE
Some IA books are not uploading

### ISSUE THREAD

**Issue by Aubreymcfato** [wikisource/ia-upload#20]
For example, this one: `ElogioCittDiArezzoImages`

I thought it was a glitch in the system, but I tried several times in several days and it's not working. Sometimes these books had a "MIME type" error, and I think it was just because there were HTML tags (like `<br/>`) inside the IA metadata, and so they were fed also in the Commons Book template. 

With this precise book, I don't get an error, but it's just not working. Neither with the @samwilson test instance...

**Comment by samwilson** [comment]
I ran the job again manually, and it uploaded this: https://commons.wikimedia.org/wiki/File:Severi_-_Elogio_citt%C3%A0_di_Arezzo.djvu
Is this all correct?

I'm trying to figure out why it got humg.

**Comment by samwilson** [comment]
The error is from djvuxmlparser:
```
djvuxmlparser jobqueue/ElogioCittDiArezzoImages/elogio\ città\ di\ Arezzo_djvu.xml_new.xml 
*** [1-16201] Failed to get specified page.
*** (XMLParser.cpp:581)
*** 'DJVU::GP<DJVU::DjVuFile> DJVU::lt_XMLParser::Impl::get_file(const DJVU::GURL&, DJVU::GUTF8String)'
```

[elogio città di Arezzo_djvu.xml_new.xml](https://github.com/wikisource/ia-upload/files/753672/elogio.citta.di.Arezzo_djvu.xml_new.xml.zip) is the DjVu XML with the filename replaced in each OBJECT element.

@alexbrollo do you know what might be causing this?

**Comment by alexbrollo** [comment]
I found a bug into djvuCl.py, it doesn't run when item name is not aligned
with file names - it happens particolarly when IA doesn't derive from a pdf
but from a zip folder of images, in this case there are three levels of
names: IA ID, zip folder, and infividual images into zip file. File names
are critical when merging _djvu.xml and djvu file; i already warn Aubrey
about that issue.

Alex

2017-02-06 6:09 GMT+01:00 Sam Wilson <notifications@github.com>:

**Comment by samwilson** [comment]
Yes, I ran into that bug too :) but I think it's fixed now.

In this case, the [ElogioCittDiArezzoImages.djvu](https://github.com/wikisource/ia-upload/files/754022/ElogioCittDiArezzoImages.djvu.zip) file is being build correctly from the individual pages' DjVus, but then failing when it tries to update it from the modified XML.

Is there any significance to the page name in the first PARAM element? I'm assuming not, since it doesn't match the original files or anything.

```xml
<OBJECT data="file://localhost/home/sam/code/ia-upload/jobqueue/ElogioCittDiArezzoImages/ElogioCittDiArezzoImages.djvu" height="1859" type="image/x.djvu" usemap="Arezzo_0017.djvu" width="1130">
  <PARAM name="PAGE" value="Arezzo_0017.djvu"/>
  <!-- cut -->
  <PARAM name="DPI" value="300"/>
</OBJECT>
<MAP name="Arezzo_0017.djvu"/>
```

I've tried rewriting it to match the filename of the single-page .djvu files that were merged, but still get the same error.

**Comment by alexbrollo** [comment]
I'll try to consider the specific case.

1. the original _images.zip is atypical, it contains a folder while it
should contain only images.
2. the name of zip is atypical, it is different from IA ID, it should be
identical
3. it is atipical too, since it contains spaces and characters different
from [a-z0-9-_]

djvuCl.py doesn't consider these atypical cases, I tested it on "good named
items"; there's a serious generalization issue inside its work flow. I
presume, that a way to fixing it sould be to convert _divu.xml into a .dsed
file; then the name of files into djvu would not be critical since dsed can
use simply the *page number*; but conversion xml->dsed is not so simple.

Alex

2017-02-06 10:27 GMT+01:00 Sam Wilson <notifications@github.com>:

**Comment by samwilson** [comment]
So it seems that the single-page DjVus have to be created from a Jpeg with a normalised name. So I've changed the script to create a `build/` directory into which the Jpegs and DjVu files are written, all with names matching the IA identifier. Then, the PARAM element for PAGE has to have its value set to the same DjVu filename (e.g. `ElogioCittDiArezzoImages_p0.djvu`).

I've updated the test site; could anyone have a crack at it and see if it's working?
