### ISSUE TITLE
IA books are stuck in queue

### ISSUE THREAD

**Issue by BodhisattwaMandal** [wikisource/ia-upload#24]
3 Bengali books which I wanted to transfer from IA to Commons are stuck in the queue for last 2-3 days. 
 The IA items are - 
* https://archive.org/details/bengalihymnsforc00unse
* https://archive.org/details/catecheticalexpo00mund
* https://archive.org/details/dialoguebetweenp00unse

**Comment by samwilson** [comment]
:-( Sorry about this. I'm implementing a log-viewing thing, so you can see what's going wrong with a job.

In this case, it's this:

    [2017-02-09 05:42:57] LOG.CRITICAL:
    Command "djvuxmlparser "/mnt/nfs/labstore-secondary-tools-project/ia-upload/ia-upload/jobqueue/bengalihymnsforc00unse/bengalihymnsforc00unse_djvu.xml_new.xml" 2>&1" exited with code 1:
    *** [1-16207] Exactly one<BODY></BODY> pair is needed.
    *** (XMLParser.cpp:604) *** 'virtual void DJVU::lt_XMLParser::Impl::parse(const DJVU::lt_XMLTags&, DJVU::GURL*)'  [] []

Which is because of [the _djvu.xml file](https://ia601504.us.archive.org/22/items/bengalihymnsforc00unse/bengalihymnsforc00unse_djvu.xml) containing only this:

    <message>language not currently OCRable</message>

:-(

(It's the same with all three items.)

The tool should check that the XML is actually DjVu XML before trying to use it. I'll get this done.

**Comment by samwilson** [comment]
bengalihymnsforc00unse is now uploaded: https://commons.wikimedia.org/wiki/File:%E0%A6%B6%E0%A6%BF%E0%A6%B6%E0%A7%81%E0%A6%A6%E0%A6%BF%E0%A6%97%E0%A7%87%E0%A6%B0_%E0%A6%A7%E0%A6%B0%E0%A7%8D%E0%A6%AE%E0%A7%8D%E0%A6%AE%E0%A6%B8%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A7%80%E0%A6%A4.djvu (as a result of my testing).

I'll now sort out the rest of the queue.

The underlying bug has been fixed.

**Comment by samwilson** [comment]
With "বাইবেল_শাস্ত্রের_অন্তঃপাতি_মার্ককর্তৃক_রচিত_মঙ্গল_সমাচার_নামক_যে_খ্রীষ্ট_বিষয়ক_উপাখ্যান_বাক্য,_তাঁহার_প্রশ্নোত্তর_ঘটিত_টীকা_পুস্তক.djvu" I get "Filenames may not be longer than 240 bytes". :-(

I'll add a restriction on the length of Commons filename that is allowed to be entered in the form.

**Comment by samwilson** [comment]
catecheticalexpo00mund is https://commons.wikimedia.org/wiki/File:%E0%A6%AC%E0%A6%BE%E0%A6%87%E0%A6%AC%E0%A7%87%E0%A6%B2_%E0%A6%B6%E0%A6%BE%E0%A6%B8%E0%A7%8D%E0%A6%A4%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%B0_%E0%A6%85%E0%A6%A8%E0%A7%8D%E0%A6%A4%E0%A6%83%E0%A6%AA%E0%A6%BE%E0%A6%A4%E0%A6%BF_%E0%A6%AE%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%95%E0%A6%95%E0%A6%B0%E0%A7%8D%E0%A6%A4%E0%A7%83%E0%A6%95_%E0%A6%B0%E0%A6%9A%E0%A6%BF%E0%A6%A4_%E0%A6%AE%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2_%E0%A6%B8%E0%A6%AE%E0%A6%BE%E0%A6%9A%E0%A6%BE%E0%A6%B0_%E0%A6%A8%E0%A6%BE%E0%A6%AE%E0%A6%95_%E0%A6%AF%E0%A7%87_%E0%A6%96%E0%A7%8D%E0%A6%B0%E0%A7%80%E0%A6%B7%E0%A7%8D%E0%A6%9F_%E0%A6%AC%E0%A6%BF%E0%A6%B7%E0%A6%AF%E0%A6%BC%E0%A6%95.djvu

dialoguebetweenp00unse is https://commons.wikimedia.org/wiki/File:%E0%A6%B0%E0%A6%BE%E0%A6%AE%E0%A6%B9%E0%A6%B0%E0%A6%BF_%E0%A6%86%E0%A6%B0_%E0%A6%8F%E0%A6%95_%E0%A6%AC%E0%A7%8D%E0%A6%AF%E0%A6%95%E0%A7%8D%E0%A6%A4%E0%A6%BF_%E0%A6%B8%E0%A6%BE%E0%A6%A7%E0%A7%81_%E0%A6%8F%E0%A6%87_%E0%A6%89%E0%A6%AD%E0%A6%AF%E0%A6%BC%E0%A7%87%E0%A6%B0_%E0%A6%95%E0%A6%A5%E0%A7%8B%E0%A6%AA%E0%A6%95%E0%A6%A5%E0%A6%A8.djvu

(Sorry, I realise you know that; I'm just recording here for the sake of it.)

So I think the underlying problem here has been fixed, and I think the more general thing of not knowing *why* an upload has failed is going to be fixed by #23 — so I'll close this.
