### ISSUE TITLE
Tracking on Wikimedia Commons

### ISSUE THREAD

**Issue by nemobis** [wikisource/ia-upload#3]
I've been using IA-upload successfully for several books. I wonder: did you ever ask commoners whether they'd prefer the tool to add a tracking category by default, as most upload tools do? For sure I'd like the summary to link back to the tool (I'll send a PR now).

In the meanwhile, I've added the tool to the "registry". https://commons.wikimedia.org/w/index.php?title=Commons%3AUpload_tools&action=historysubmit&diff=151487057&oldid=149470163
I didnt' file a tool page description in wikisource.org, is there one? If not, IMHO better create something (even just a redirect to the section above) at [[commons:Commons:IA-upload]].

**Comment by Tpt** [comment]
> is there one?

I don't think there is one yet. Thank you for the addition to the "registry"

**Comment by samwilson** [comment]
Not quite as good as a category (because it can possibly change over time) but there every upload from the tool is tagged (as `OAuth CID: 40`), and can be viewed here:

https://commons.wikimedia.org/w/index.php?title=Special:RecentChanges&tagfilter=OAuth+CID%3A+40

**Comment by samwilson** [comment]
Should we add `[[Category:Uploaded with IA Upload]]` and add it to https://commons.wikimedia.org/wiki/Category:Files_by_upload_tool ?

And if so, I guess {{subst:unc}} should still be included? Because the 'uploaded with' category isn't really a subject category?

**Comment by Tpt** [comment]
I believe that we could already track the upload by filtering the edits with ia-upload OAuth tokens.

**Comment by samwilson** [comment]
@tpt: do you think we don't need an upload category then? Other upload tools have one, that's all.

Do you think the oauth tag is sufficient?

**Comment by Tpt** [comment]
OAuth tag is sufficient to track the recent uploads done using the tool: https://commons.wikimedia.org/w/index.php?namespace=&tagfilter=OAuth+CID%3A+40&translations=filter&title=Special%3ARecentChanges

But if we want to do things like "all french books uploaded using IA-Upload" the tracking category is probably the way to go because it allows to do category intersections (it seems difficult to do intersection of things that are on page level (e.g. category) and on edit level (e.g. edit tags like "edit done with the IA-Upload OAuth token")

**Comment by samwilson** [comment]
I've added https://commons.wikimedia.org/wiki/Category:Uploaded_with_IA_Upload

It still uses {{unc}} though, because other categories will still be required sometimes.

Prod site updated.
